# analyzer:
#   errors:
#     inference_failure_on_function_invocation: ignore
# include: package:very_good_analysis/analysis_options.yaml

# linter:
#   rules:
#     use_build_context_synchronously: false
#     public_member_api_docs: false
#     type_annotate_public_apis: false
#     lines_longer_than_80_chars: false
