name: Build Flutter APK

on:
  push:
    branches:
      - main  # or specify the branch you want to trigger the build on
  pull_request:
    branches:
      - main  # or specify the branch you want to trigger the build on

jobs:
  build:
    runs-on: macos-latest  # Use macOS for building

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Check out the code from the repo

      - name: Install Flutter using Homebrew
        run: |
          brew update
          brew install --cask flutter  # Install the latest stable Flutter version via Homebrew

      - name: Set Flutter version
        run: flutter --version  # Check the installed Flutter version

      - name: Install dependencies
        run: flutter pub get  # Get Flutter dependencies

      - name: Build APK
        run: flutter build apk --release  # Build the release APK

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3  # Upload the APK as an artifact
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/app-release.apk  # Path to the built APK
