name: Build Flutter APK

on:
  push:
    branches:
      - main  # or specify the branch you want to trigger the build on
  pull_request:
    branches:
      - main  # or specify the branch you want to trigger the build on

jobs:
  build:
    runs-on: macos-latest  # Use macOS for building

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Check out the code from the repo

      - name: Set up Flutter
        uses: subosito/flutter-action@v2  # Use the latest Flutter action
        with:
          flutter-version: "3.1.5"  # Match the required version from pubspec.yaml

      - name: Install dependencies
        run: flutter pub get  # Get Flutter dependencies

      - name: Build APK
        run: flutter build apk --release  # Build the release APK

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3  # Upload the APK as an artifact
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/app-release.apk  # Path to the built APK
