name: Build and Release Flutter APK

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'  # Adjust to your project's Java version

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: 'stable'  # Or specify a specific version

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-caches-${{ runner.os }}-${{ hashFiles('**/gradle.properties') }}
          restore-keys: |
            gradle-caches-${{ runner.os }}-

      - name: Cache Flutter packages
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: flutter-pub-cache-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            flutter-pub-cache-${{ runner.os }}-

      - name: Clean Flutter project
        run: flutter clean

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --no-clean

      - name: Upload APK to GitHub Release
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0  # Replace with your desired tag name
          release_name: Release v1.0.0
          draft: false
          prerelease: false
          body: |
            This is the first release of my Flutter app.
          artifacts: flutter-apk
